#server.port: 8081

spring:
  profiles:
    active: qa
#   cloud:
#     config:
#       uri: http://localhost:8888

greeting: "Hello cloud greeting message hello world in java. test home hello"
mydbpassword: "myencpass"
