server.port: 8080

spring:
  profiles:
    active: qa
  cloud:
    config:
      uri: http://localhost:8888

greeting: "Hello cloud greeting message hello world in java. test"
mydbpassword: "myencpass"