#server.port: 8082

spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888

greeting: "This is greeting message. serving the detail from sampleapp.yml file."
mydbpassword: "12345678"
