#server.port: 8082

spring:
  profiles:
    active: dev
  cloud:
    config:
      uri: http://localhost:8888

#greeting: "default sampleapp.yml file inside sampleapp folder."
mydbpassword: "12345678"