logging.level.org.springframework: debug

spring:
  datasource:
      driver: org.postgresql.Driver
      password: '{cipher}fdb35fccfda9a0da02aef5314bc9b13ec5ed7fe49774b943135bbb227a55f1d4'
      platform: postgres
      url: jdbc:postgresql://192.168.1.7:5432/postgresqa
      username: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    generate-ddl: true
    hibernate.ddl-auto: update
    properties.hibernate.jdbc.lob.non_contextual_creation: true

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS: false

#active env check
active-env: qaoutside-environment
greeting: "greeting from sampleapp-qa hello.yml file."

# kubernates secret key
